
export const people = [
    {
        id: 1,
        name: 'Thamirys Oliveira 🌷🤎',
        role: 'Coordenadora do Grupo Psicoeducativo',
        profession: 'Psicóloga - CRP 21/05722',
        bio: 'Sou psicóloga formada pela Universidade Estadual do Piauí (UESPI) e no projeto sou responsável pelo Grupo Psicoeducativo: Vozes em Diálogo. Como pesquisadora, atuo nas áreas de raça, gênero, religiosidade e saúde mental, sempre buscando compreender e transformar as complexas realidades sociais que nos cercam. Minha paixão pelo campo da psicologia social me impulsiona a trabalhar para o empoderamento das pessoas, promovendo o diálogo e a compreensão mútua. Acredito que, através do trabalho coletivo e da educação, podemos construir uma sociedade mais justa e inclusiva, onde cada voz é ouvida e valorizada.',
        socialLink: 'https://www.instagram.com/oliv.thamirys?igsh=NzZ3dnFxZTlnZDk3&utm_source=qr',
        tags: ['psicologo', 'gestao',],
        imageLink: '/images/pessoas/thamirys.jpg',
        alt: 'Foto de Lucas Rafael',
    },
    {
        id: 2,
        name: 'Waldir Santos ❤️🎶',
        role: 'Coordenadora do Grupo Psicoeducativo',
        profession: 'Professor de música',
        bio: 'Sou um multiartista licenciado em Música pela Universidade Federal do Piauí (UFPI). Apaixonado pela mobilização coletiva e social, acredito profundamente no poder transformador da arte para alterar e enriquecer a realidade em que está inserida.',
        socialLink: 'https://www.instagram.com/oliv.thamirys?igsh=NzZ3dnFxZTlnZDk3&utm_source=qr',
        tags: ['professor', 'gestao',],
        imageLink: '/images/pessoas/waldir.jpg',
        alt: 'Foto de Lucas Rafael',
    },
    {
        id: 3,
        name: 'Francisco Carlos(mimi)  🎸👨🏾‍🏫',
        role: 'Diretor do projeto e professor de música',
        profession: 'Professor de música',
        bio: 'Sou professor de música com mais de 30 anos de experiência em projetos sociais e atualmente presidente da Fundação Cultural Proarte, instituição responsável pelo nosso projeto. Como um grande mobilizador cultural na sociedade de José de Freitas, dedico minha vida a transformar a comunidade através da arte. ',
        socialLink: 'https://www.instagram.com/oliv.thamirys?igsh=NzZ3dnFxZTlnZDk3&utm_source=qr',
        tags: ['professor', 'gestao',],
        imageLink: '/images/pessoas/mimi.jpg',
        alt: 'Foto de Lucas Rafael',
    },
    {
        id: 4,
        name: 'Jaciane de Oliveira 🌱☀️',
        role: 'Psicóloga no Grupo Psicoeducativo',
        profession: 'Psicoloca - CRP 21/05893',
        bio: 'Sou psicóloga com bacharelado e licenciatura em Psicologia pela Universidade Estadual do Piauí (UESPI) e sou voluntária do projeto, atuando na mediação do Grupo Psicoeducativo “Vozes em Diálogo”. Como pesquisadora, estudo as áreas de Psicologia Escolar Educacional, violência intrafamiliar, relação família-escola e direitos das crianças e adolescentes, no intuito de contribuir para a construção de conhecimentos com retorno efetivo para a comunidade e que nos levem a relações mais respeitosas. Sou fruto integralmente da educação pública e acredito no potencial da educação para a transformação da realidade social. Dessa forma, entendo os ambientes educacionais como espaços ricos para o desenvolvimento pessoal e coletivo. Na minha trajetória, valorizo a escuta e o diálogo como formas de crescimento e transformação mútua, capazes de promover um impacto positivo e duradouro em nossa sociedade.',
        socialLink: 'https://www.instagram.com/jaciane.oliveiras?igsh=MTluZTU1aTl3aDBncw==',
        tags: ['psicologo'],
        imageLink: '/images/pessoas/jaciane.jpg',
        alt: 'Foto de Lucas Rafael',
    },
    {
        id: 5,
        name: 'Deys Rodrigues 🪴🌵',
        role: 'Desenvolvedora do site projeto',
        profession: 'Web developer com foco em front-end',
        bio: '"Programadora, Ilustradora e estudante de uix design , criadora do site do projeto e fã resoluta de piano classico e doce de leite."',
        socialLink: 'https://www.instagram.com/venushima',
        tags: ['dev'],
        imageLink: '/images/deys.jpg',
        alt: 'Foto de Lucas Rafael',
    },
    {
        id: 6,
        name: 'Lucas Rafael 🎸🎸',
        role: 'Professor de Música',
        profession: 'Luthier',
        bio: ' "Artista, musico, gosto de jogos em geral, trabalho como luthier e professor de musica no projeto. Gosto de todo tipo de animal que nao queira um pedaco de mim kkkk"',
        socialLink: 'https://www.instagram.com/venushima',
        tags: ['professor'],
        imageLink: '/images/pessoas/lucas.jpg',
        alt: 'Foto de Lucas Rafael',
    },
    {
        id: 7,
        name: 'Marcos Ribeiro 🎶🎸',
        role: 'Professor de Música',
        profession: 'Se graduando em engenharia agronomica',
        bio: '"Programadora, Ilustradora e estudante de uix design , criadora do site do projeto e fã resoluta de piano classico e doce de leite.""Sou apaixonado por música principalmente da década de 80, aficionado por cinema de quadrinhos e ficção científica, e botafoguense de alma e coração." ',
        socialLink: 'https://www.instagram.com/venushima',
        tags: ['professor'],
        imageLink: '/images/pessoas/marcos.jpg',
        alt: 'Foto de Marcos Ribeiro',
    },




    // Adicione mais pessoas conforme necessário
];
